info:
  serviceName: @project.artifactId@
  version: @project.version@
  description: @project.description@
  businessSide: 研发部
  jdk-version: @java.version@
  spring-boot.version: @spring-boot.version@
  spring-cloud.version: @spring-cloud.version@
  author: yangrd


management:
  endpoints:
    web:
      exposure:
        include: mappings,env,health,metrics,prometheus


logging:
  level:
    root: INFO
    com.scg.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#  file: /tmp/${spring.application.name}.log



spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://192.168.2.54:9411
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: any
        provider:
          uaa:
            authorization-uri: http://localhost:8087/oauth/authorize
            token-uri: http://localhost:8087/oauth/token
            user-info-uri: http://localhost:8087/userinfo
            user-name-attribute: name
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1

server:
  port: 8086
