info:
#  serviceName: @project.artifactId@
  version: @project.version@
  description: @project.description@
  businessSide: 研发部
  jdk-version: @java.version@
  spring-boot.version: @spring-boot.version@
  spring-cloud.version: @spring-cloud.version@
  author: yangrd


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: DEBUG
  file: /tmp/${spring.application.name}.log

server:
  port: 9080
feign:
  hystrix:
    enabled: true
spring:
  profiles:
    active: dev
