info:
  serviceName: @project.artifactId@
  version: @project.version@
  description: @project.description@
  businessSide: 研发部
  jdk-version: @java.version@
  spring-boot.version: @spring-boot.version@
  spring-cloud.version: @spring-cloud.version@
  author: yangrd


management:
  endpoints:
    web:
      exposure:
        include: mappings,env,health


logging:
  level:
    org.springframework: DEBUG

server:
  port: 8087

feign:
  hystrix:
    enabled: true
spring:
  profiles:
    active: dev
