info:
  serviceName: @project.artifactId@
  version: @project.version@
  description: @project.description@
  businessSide: 研发部
  jdk-version: @java.version@
  spring-boot.version: @spring-boot.version@
  spring-cloud.version: @spring-cloud.version@
  author: yangrd


management:
  endpoints:
    web:
      exposure:
        include: mappings,env,health,metrics,prometheus


logging:
  level:
    root: INFO
    com.scg.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
  file: /tmp/${spring.application.name}.log


server:
  port: 8087

feign:
  hystrix:
    enabled: true
spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://192.168.2.54:9411
