info:
  serviceName: @project.artifactId@
  version: @project.version@
  description: @project.description@
  businessSide: 研发部
  jdk-version: @java.version@
  spring-boot.version: @spring-boot.version@
  spring-cloud.version: @spring-cloud.version@
  author: yangrd


management:
  endpoints:
    web:
      exposure:
        include: mappings,env,health


logging:
  level:
    org.springframework: DEBUG

server:
  port: 8087

feign:
  hystrix:
    enabled: true
spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${server.port}/.well-known/jwks.json

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
